# Generated by Django 3.0.2 on 2020-01-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myNewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupformsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('screenname', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('confirmpassword', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SignUp_User_Details',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'student_dtails'},
        ),
    ]
